export  const patients = [
    {
      id: 1,
      name: 'Sarah Johnson',
      age: 45,
      gender: 'Female',
      lastVisit: '2023-10-15',
      nextAppointment: '2023-11-15',
      status: 'stable',
      condition: 'Hypertension',
      bloodType: 'A+',
      avatar: '/avatars/sarah.jpg',
      initials: 'SJ',
      treatmentProgress: 75,
      treatmentPlan: 'Hypertension Management',
      startDate: '2023-06-10',
      physician: 'Dr. Smith'
    },
    {
      id: 2,
      name: 'Michael Chen',
      age: 62,
      gender: 'Male',
      lastVisit: '2023-10-12',
      nextAppointment: '2023-10-29',
      status: 'critical',
      condition: 'Diabetes Type II',
      bloodType: 'O-',
      avatar: '/avatars/michael.jpg',
      initials: 'MC',
      treatmentProgress: 40,
      treatmentPlan: 'Diabetes Control',
      startDate: '2023-05-22',
      physician: 'Dr. Johnson'
    },
    {
      id: 3,
      name: 'Emma Rodriguez',
      age: 28,
      gender: 'Female',
      lastVisit: '2023-10-10',
      nextAppointment: '2023-11-05',
      status: 'recovering',
      condition: 'Migraine',
      bloodType: 'B+',
      avatar: '/avatars/emma.jpg',
      initials: 'ER',
      treatmentProgress: 90,
      treatmentPlan: 'Migraine Prevention',
      startDate: '2023-07-15',
      physician: 'Dr. Williams'
    },
    {
      id: 4,
      name: 'James Wilson',
      age: 51,
      gender: 'Male',
      lastVisit: '2023-10-08',
      nextAppointment: '2023-11-10',
      status: 'stable',
      condition: 'High Cholesterol',
      bloodType: 'AB+',
      avatar: '/avatars/james.jpg',
      initials: 'JW',
      treatmentProgress: 60,
      treatmentPlan: 'Cholesterol Management',
      startDate: '2023-08-05',
      physician: 'Dr. Smith'
    }
  ];

  // Sample treatment data
 export const treatments = [
    {
      id: 1,
      patientId: 1,
      patientName: 'Sarah Johnson',
      planName: 'Hypertension Management',
      startDate: '2023-06-10',
      endDate: '2023-12-10',
      status: 'active',
      progress: 75,
      medications: ['Lisinopril 10mg daily', 'Metoprolol 25mg daily'],
      interventions: ['Diet modification', 'Exercise regimen', 'Regular BP monitoring'],
      goals: ['Maintain BP below 130/80', 'Lose 10 lbs', 'Reduce sodium intake'],
      lastReview: '2023-10-15',
      nextReview: '2023-11-15',
      physician: 'Dr. Smith'
    },
    {
      id: 2,
      patientId: 2,
      patientName: 'Michael Chen',
      planName: 'Diabetes Control',
      startDate: '2023-05-22',
      endDate: '2024-05-22',
      status: 'active',
      progress: 40,
      medications: ['Metformin 500mg twice daily', 'Insulin Glargine 20 units nightly'],
      interventions: ['Blood glucose monitoring', 'Carbohydrate counting', 'Foot care education'],
      goals: ['A1C below 7%', 'Fasting glucose under 130 mg/dL', 'Weight loss of 15 lbs'],
      lastReview: '2023-10-12',
      nextReview: '2023-10-29',
      physician: 'Dr. Johnson'
    },
    {
      id: 3,
      patientId: 3,
      patientName: 'Emma Rodriguez',
      planName: 'Migraine Prevention',
      startDate: '2023-07-15',
      endDate: '2023-12-15',
      status: 'active',
      progress: 90,
      medications: ['Sumatriptan 50mg as needed', 'Propranolol 40mg daily'],
      interventions: ['Stress management', 'Sleep hygiene', 'Trigger identification'],
      goals: ['Reduce migraine frequency by 50%', '< 2 migraines per month', 'Improve quality of life'],
      lastReview: '2023-10-10',
      nextReview: '2023-11-05',
      physician: 'Dr. Williams'
    },
    {
      id: 4,
      patientId: 4,
      patientName: 'James Wilson',
      planName: 'Cholesterol Management',
      startDate: '2023-08-05',
      endDate: '2024-02-05',
      status: 'active',
      progress: 60,
      medications: ['Atorvastatin 20mg daily', 'Aspirin 81mg daily'],
      interventions: ['Dietary changes', 'Aerobic exercise', 'Weight management'],
      goals: ['LDL below 100 mg/dL', 'Total cholesterol below 200 mg/dL', 'Lose 12 lbs'],
      lastReview: '2023-10-08',
      nextReview: '2023-11-10',
      physician: 'Dr. Smith'
    },
    {
      id: 5,
      patientId: 1,
      patientName: 'Sarah Johnson',
      planName: 'Weight Management',
      startDate: '2023-01-15',
      endDate: '2023-07-15',
      status: 'completed',
      progress: 100,
      medications: [],
      interventions: ['Calorie restriction', 'Exercise program', 'Nutrition counseling'],
      goals: ['Lose 15 lbs', 'Reduce BMI to 25', 'Improve fitness level'],
      lastReview: '2023-07-10',
      nextReview: 'N/A',
      physician: 'Dr. Smith'
    }
  ];
