export const allDoctors=[
  {
    id: 1,
    name: "Dr. Sarah Johnson",
    specialty: "Cardiology",
    email: "sarah.johnson@hospital.com",
    phone: "(555) 123-4567",
    status: "Active",
  },
  {
    id: 2,
    name: "Dr. Michael Chen",
    specialty: "Neurology",
    email: "michael.chen@hospital.com",
    phone: "(555) 234-5678",
    status: "Active",
  },
  {
    id: 3,
    name: "Dr. Emily Wilson",
    specialty: "Pediatrics",
    email: "emily.wilson@hospital.com",
    phone: "(555) 345-6789",
    status: "On Leave",
  },
  {
    id: 4,
    name: "Dr. James Anderson",
    specialty: "Orthopedics",
    email: "james.anderson@hospital.com",
    phone: "(555) 456-7890",
    status: "Active",
  },
  {
    id: 5,
    name: "Dr. Linda Martinez",
    specialty: "Dermatology",
    email: "linda.martinez@hospital.com",
    phone: "(555) 567-8901",
    status: "Active",
  },
  {
    id: 6,
    name: "Dr. Robert Lee",
    specialty: "Oncology",
    email: "robert.lee@hospital.com",
    phone: "(555) 678-9012",
    status: "Retired",
  },
  {
    id: 7,
    name: "Dr. Patricia Brown",
    specialty: "Gynecology",
    email: "patricia.brown@hospital.com",
    phone: "(555) 789-0123",
    status: "Active",
  },
  {
    id: 8,
    name: "Dr. William Davis",
    specialty: "Radiology",
    email: "william.davis@hospital.com",
    phone: "(555) 890-1234",
    status: "Active",
  },
  {
    id: 9,
    name: "Dr. Jennifer Wilson",
    specialty: "Psychiatry",
    email: "jennifer.wilson@hospital.com",
    phone: "(555) 901-2345",
    status: "On Leave",
  },
  {
    id: 10,
    name: "Dr. Charles Thompson",
    specialty: "Gastroenterology",
    email: "charles.thompson@hospital.com",
    phone: "(555) 012-3456",
    status: "Active",
  },
  {
    id: 11,
    name: "Dr. Elizabeth Garcia",
    specialty: "Endocrinology",
    email: "elizabeth.garcia@hospital.com",
    phone: "(555) 213-4567",
    status: "Active",
  },
  {
    id: 12,
    name: "Dr. Matthew Robinson",
    specialty: "Pulmonology",
    email: "matthew.robinson@hospital.com",
    phone: "(555) 324-5678",
    status: "Active",
  },
  {
    id: 13,
    name: "Dr. Barbara Clark",
    specialty: "Nephrology",
    email: "barbara.clark@hospital.com",
    phone: "(555) 435-6789",
    status: "Retired",
  },
  {
    id: 14,
    name: "Dr. Steven Lewis",
    specialty: "Rheumatology",
    email: "steven.lewis@hospital.com",
    phone: "(555) 546-7890",
    status: "Active",
  },
  {
    id: 15,
    name: "Dr. Angela Young",
    specialty: "Allergy & Immunology",
    email: "angela.young@hospital.com",
    phone: "(555) 657-8901",
    status: "Active",
  },
  {
    id: 16,
    name: "Dr. George Walker",
    specialty: "Ophthalmology",
    email: "george.walker@hospital.com",
    phone: "(555) 768-9012",
    status: "Active",
  },
  {
    id: 17,
    name: "Dr. Karen Hall",
    specialty: "Emergency Medicine",
    email: "karen.hall@hospital.com",
    phone: "(555) 879-0123",
    status: "On Leave",
  },
  {
    id: 18,
    name: "Dr. Brian Allen",
    specialty: "Urology",
    email: "brian.allen@hospital.com",
    phone: "(555) 980-1234",
    status: "Active",
  },
  {
    id: 19,
    name: "Dr. Donna Scott",
    specialty: "Family Medicine",
    email: "donna.scott@hospital.com",
    phone: "(555) 091-2345",
    status: "Active",
  },
  {
    id: 20,
    name: "Dr. Kevin Adams",
    specialty: "Anesthesiology",
    email: "kevin.adams@hospital.com",
    phone: "(555) 102-3456",
    status: "Active",
  }
]
