export const alergieslist = [
  {
    id: 1,
    name: "Penicillin",
    reaction: "Rash",
    severity: "Moderate",
    notes: "Discovered in childhood",
  },
  {
    id: 2,
    name: "Shellfish",
    reaction: "Hives",
    severity: "Severe",
    notes: "Anaphylactic reaction",
  },
  {
    id: 3,
    name: "Peanuts",
    reaction: "Swelling",
    severity: "Severe",
    notes: "Carries epinephrine auto-injector",
  },
  {
    id: 4,
    name: "Latex",
    reaction: "Itching",
    severity: "Mild",
    notes: "Avoids latex gloves",
  },
  {
    id: 5,
    name: "Bee Stings",
    reaction: "Anaphylaxis",
    severity: "Severe",
    notes: "Requires immediate medical attention",
  },
  {
    id: 6,
    name: "Aspirin",
    reaction: "Stomach pain",
    severity: "Moderate",
    notes: "Alternative painkillers prescribed",
  },
  {
    id: 7,
    name: "Milk",
    reaction: "Nausea",
    severity: "Mild",
    notes: "Lactose intolerance suspected",
  },
  {
    id: 8,
    name: "Eggs",
    reaction: "Hives",
    severity: "Moderate",
    notes: "Avoids baked goods with eggs",
  },
  {
    id: 9,
    name: "Tree Nuts",
    reaction: "Swelling",
    severity: "Severe",
    notes: "Avoids all nut-based foods",
  },
  {
    id: 10,
    name: "Dust Mites",
    reaction: "Sneezing",
    severity: "Mild",
    notes: "Worsens during winter",
  },
  {
    id: 11,
    name: "Pollen",
    reaction: "Runny nose",
    severity: "Moderate",
    notes: "Seasonal allergy",
  },
  {
    id: 12,
    name: "Mold",
    reaction: "Coughing",
    severity: "Moderate",
    notes: "Triggered in damp areas",
  },
  {
    id: 13,
    name: "Sulfa Drugs",
    reaction: "Rash",
    severity: "Severe",
    notes: "Avoided during prescriptions",
  },
  {
    id: 14,
    name: "Soy",
    reaction: "Itchy throat",
    severity: "Mild",
    notes: "Avoids soy-based foods",
  },
  {
    id: 15,
    name: "Wheat",
    reaction: "Bloating",
    severity: "Moderate",
    notes: "Possible gluten sensitivity",
  },
  {
    id: 16,
    name: "Cat Dander",
    reaction: "Sneezing",
    severity: "Mild",
    notes: "Avoids prolonged exposure to cats",
  },
  {
    id: 17,
    name: "Dog Dander",
    reaction: "Watery eyes",
    severity: "Mild",
    notes: "Manages with antihistamines",
  },
  {
    id: 18,
    name: "Strawberries",
    reaction: "Hives",
    severity: "Moderate",
    notes: "Noticed in teenage years",
  },
  {
    id: 19,
    name: "Chocolate",
    reaction: "Migraines",
    severity: "Moderate",
    notes: "Triggered by overconsumption",
  },
  {
    id: 20,
    name: "Perfumes",
    reaction: "Headache",
    severity: "Mild",
    notes: "Strong fragrances cause discomfort",
  },
];

export const conditionlist=[
  {
    id: 1,
    name: "Type 2 Diabetes",
    date: "2018-05-15",
    severity: "Moderate",
    notes: "Controlled with medication",
  },
  {
    id: 2,
    name: "Hypertension",
    date: "2017-11-22",
    severity: "Mild",
    notes: "Regular monitoring required",
  },
  {
    id: 3,
    name: "Asthma",
    date: "2015-03-10",
    severity: "Moderate",
    notes: "Seasonal flare-ups",
  },
  {
    id: 4,
    name: "Chronic Kidney Disease",
    date: "2019-09-01",
    severity: "Severe",
    notes: "Requires nephrologist follow-up",
  },
  {
    id: 5,
    name: "Osteoarthritis",
    date: "2016-07-14",
    severity: "Moderate",
    notes: "Joint pain managed with therapy",
  },
  {
    id: 6,
    name: "Hypothyroidism",
    date: "2020-02-18",
    severity: "Mild",
    notes: "Stable with levothyroxine",
  },
  {
    id: 7,
    name: "Coronary Artery Disease",
    date: "2018-12-05",
    severity: "Severe",
    notes: "History of stent placement",
  },
  {
    id: 8,
    name: "Depression",
    date: "2014-10-09",
    severity: "Moderate",
    notes: "Under psychiatric care",
  },
  {
    id: 9,
    name: "Anxiety Disorder",
    date: "2016-06-21",
    severity: "Mild",
    notes: "Managed with counseling",
  },
  {
    id: 10,
    name: "Chronic Obstructive Pulmonary Disease (COPD)",
    date: "2019-04-12",
    severity: "Severe",
    notes: "Requires inhalers",
  },
  {
    id: 11,
    name: "Gastroesophageal Reflux Disease (GERD)",
    date: "2017-01-30",
    severity: "Mild",
    notes: "Lifestyle modifications help",
  },
  {
    id: 12,
    name: "Psoriasis",
    date: "2015-08-19",
    severity: "Moderate",
    notes: "Topical creams prescribed",
  },
  {
    id: 13,
    name: "Migraine",
    date: "2018-03-11",
    severity: "Moderate",
    notes: "Triggered by stress",
  },
  {
    id: 14,
    name: "Obesity",
    date: "2016-12-07",
    severity: "Moderate",
    notes: "Weight management ongoing",
  },
  {
    id: 15,
    name: "Sleep Apnea",
    date: "2019-11-23",
    severity: "Severe",
    notes: "Uses CPAP machine",
  },
  {
    id: 16,
    name: "Rheumatoid Arthritis",
    date: "2015-09-16",
    severity: "Severe",
    notes: "Regular rheumatology visits",
  },
  {
    id: 17,
    name: "Chronic Back Pain",
    date: "2013-04-04",
    severity: "Moderate",
    notes: "Physical therapy recommended",
  },
  {
    id: 18,
    name: "Anemia",
    date: "2017-05-28",
    severity: "Mild",
    notes: "Iron supplements prescribed",
  },
  {
    id: 19,
    name: "Glaucoma",
    date: "2020-08-02",
    severity: "Moderate",
    notes: "Eye drops daily",
  },
  {
    id: 20,
    name: "Allergic Rhinitis",
    date: "2012-03-15",
    severity: "Mild",
    notes: "Triggered by seasonal pollen",
  },
];

export const medicationsList = [
  {
    id: 1,
    name: "Metformin",
    dosage: "500mg",
    frequency: "Twice daily",
    startDate: "2018-05-20",
    notes: "For diabetes",
  },
  {
    id: 2,
    name: "Lisinopril",
    dosage: "10mg",
    frequency: "Daily",
    startDate: "2017-12-01",
    notes: "For blood pressure",
  },
  {
    id: 3,
    name: "Albuterol",
    dosage: "90mcg",
    frequency: "As needed",
    startDate: "2015-03-15",
    notes: "Inhaler for asthma",
  },
  {
    id: 4,
    name: "Atorvastatin",
    dosage: "20mg",
    frequency: "Daily",
    startDate: "2019-01-10",
    notes: "For cholesterol",
  },
  {
    id: 5,
    name: "Levothyroxine",
    dosage: "75mcg",
    frequency: "Daily",
    startDate: "2020-03-05",
    notes: "For hypothyroidism",
  },
  {
    id: 6,
    name: "Amlodipine",
    dosage: "5mg",
    frequency: "Daily",
    startDate: "2018-06-25",
    notes: "For hypertension",
  },
  {
    id: 7,
    name: "Omeprazole",
    dosage: "20mg",
    frequency: "Daily",
    startDate: "2017-09-12",
    notes: "For GERD",
  },
  {
    id: 8,
    name: "Sertraline",
    dosage: "50mg",
    frequency: "Daily",
    startDate: "2016-11-18",
    notes: "For depression",
  },
  {
    id: 9,
    name: "Hydrochlorothiazide",
    dosage: "25mg",
    frequency: "Daily",
    startDate: "2019-04-01",
    notes: "For blood pressure",
  },
  {
    id: 10,
    name: "Warfarin",
    dosage: "5mg",
    frequency: "Daily",
    startDate: "2015-07-09",
    notes: "Blood thinner",
  },
  {
    id: 11,
    name: "Insulin Glargine",
    dosage: "20 units",
    frequency: "Nightly",
    startDate: "2018-10-20",
    notes: "For diabetes",
  },
  {
    id: 12,
    name: "Montelukast",
    dosage: "10mg",
    frequency: "Daily",
    startDate: "2016-02-14",
    notes: "For asthma",
  },
  {
    id: 13,
    name: "Gabapentin",
    dosage: "300mg",
    frequency: "Three times daily",
    startDate: "2019-08-22",
    notes: "For nerve pain",
  },
  {
    id: 14,
    name: "Prednisone",
    dosage: "10mg",
    frequency: "As directed",
    startDate: "2020-01-15",
    notes: "For inflammation",
  },
  {
    id: 15,
    name: "Furosemide",
    dosage: "40mg",
    frequency: "Daily",
    startDate: "2017-04-30",
    notes: "For fluid retention",
  },
  {
    id: 16,
    name: "Clopidogrel",
    dosage: "75mg",
    frequency: "Daily",
    startDate: "2018-12-11",
    notes: "Prevents blood clots",
  },
  {
    id: 17,
    name: "Fluticasone",
    dosage: "50mcg",
    frequency: "As needed",
    startDate: "2016-05-09",
    notes: "Nasal spray for allergies",
  },
  {
    id: 18,
    name: "Paracetamol",
    dosage: "500mg",
    frequency: "As needed",
    startDate: "2014-08-21",
    notes: "For pain relief",
  },
  {
    id: 19,
    name: "Diazepam",
    dosage: "5mg",
    frequency: "As needed",
    startDate: "2019-09-07",
    notes: "For anxiety",
  },
  {
    id: 20,
    name: "Insulin Lispro",
    dosage: "10 units",
    frequency: "Before meals",
    startDate: "2018-06-30",
    notes: "Rapid-acting insulin",
  },
];
